"""
初期データ投入スクリプト。
URLとメインKWのペアをDBに登録する。
同じURLが複数KWを持つ場合は最初のKWをメインKWとし、追加KWはarticle_keywordsに登録。
"""
import database as db

RAW = [
    ("https://www.w2solution.co.jp/useful_info_ec/company-app-ec/", "会社アプリEC"),
    ("https://www.w2solution.co.jp/useful_info_ec/7197/", None),
    ("https://www.w2solution.co.jp/useful_info_ec/1713/", None),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-cart/", "D2C カート"),
    ("https://www.w2solution.co.jp/useful_info_ec/628/", None),
    ("https://www.w2solution.co.jp/useful_info_ec/apparel_netshop/", "アパレル ネットショップ"),
    ("https://www.w2solution.co.jp/useful_info_ec/purchasing-data-management/", "購買データ管理"),
    ("https://www.w2solution.co.jp/useful_info_ec/hikaku-asp-mall/", "ECサイト 無料ASP"),
    ("https://www.w2solution.co.jp/useful_info_ec/pos-regi/", "POSレジ"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-supplement/", "D2C サプリ"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-apparel-example/", "D2C アパレル"),
    ("https://www.w2solution.co.jp/useful_info_ec/production_management_system/", "EC 生産管理システム"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-healthy-food/", "D2C 健康食品"),
    ("https://www.w2solution.co.jp/useful_info_ec/ecequation/", "EC 売上法則"),
    ("https://www.w2solution.co.jp/useful_info_ec/supplement_netshop/", "ネットショップ サプリメント事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/4816/", "定期通販カートシステム 選定基準"),
    ("https://www.w2solution.co.jp/useful_info_ec/1014/", "EC 不正アクセス"),
    ("https://www.w2solution.co.jp/useful_info_ec/849/", "越境EC 言語"),
    ("https://www.w2solution.co.jp/useful_info_ec/btob-ec-ranking/", "ECサイト BtoB ランキング"),
    ("https://www.w2solution.co.jp/useful_info_ec/1721/", "ECサイト運営"),
    ("https://www.w2solution.co.jp/useful_info_ec/8526/", "EC化率"),
    ("https://www.w2solution.co.jp/useful_info_ec/1110/", "EC 売上"),
    ("https://www.w2solution.co.jp/useful_info_ec/onlineshop-howto/", "ネットショップ構築"),
    ("https://www.w2solution.co.jp/useful_info_ec/omo-omni/", "OMOとは"),
    ("https://www.w2solution.co.jp/useful_info_ec/content-marketing/", "EC コンテンツマーケティング"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-case/", "D2C 事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/639/", "ネットショップ クレーム"),
    ("https://www.w2solution.co.jp/useful_info_ec/subscription-case/", "サブスクEC"),
    ("https://www.w2solution.co.jp/useful_info_ec/subscription/", "サブスク 事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/1684/", "EC プロモーション"),
    ("https://www.w2solution.co.jp/useful_info_ec/3859/", "EC 事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/netshop-work/", "ネットショップ業務"),
    ("https://www.w2solution.co.jp/useful_info_ec/smallscale_ec/", "小規模ECサイト"),
    ("https://www.w2solution.co.jp/useful_info_ec/netsop-example/", "ネットショップ 事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/business-strategy/", "EC 事業戦略"),
    ("https://www.w2solution.co.jp/useful_info_ec/783/", "EC リスク"),
    ("https://www.w2solution.co.jp/useful_info_ec/possystem-ec-linkage/", "EC POSシステム"),
    ("https://www.w2solution.co.jp/useful_info_ec/sfa-about/", "EC SFA"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-warehouse/", "EC物流倉庫 委託"),
    ("https://www.w2solution.co.jp/useful_info_ec/697/", "ECサイト ABテスト"),
    ("https://www.w2solution.co.jp/useful_info_ec/distribution-meeting/", "頒布会とは"),
    ("https://www.w2solution.co.jp/useful_info_ec/1094/", "EC 直帰率"),
    ("https://www.w2solution.co.jp/useful_info_ec/line-mini-app/", "EC LINEミニアプリ"),
    ("https://www.w2solution.co.jp/useful_info_ec/company-consulting/", "ECコンサルティング"),
    ("https://www.w2solution.co.jp/useful_info_ec/759/", "EC 検索エンジン"),
    ("https://www.w2solution.co.jp/useful_info_ec/772/", "EC レビュー"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-company/", "EC 物流 おすすめ"),
    ("https://www.w2solution.co.jp/useful_info_ec/customerdata-management/", "EC 顧客データ管理"),
    ("https://www.w2solution.co.jp/useful_info_ec/8445/", "ECプラットフォーム"),
    ("https://www.w2solution.co.jp/useful_info_ec/1102/", "EC決済"),
    ("https://www.w2solution.co.jp/useful_info_ec/netshop-osusume/", "ネットショップ開業 おすすめ"),
    ("https://www.w2solution.co.jp/useful_info_ec/6697/", "EC CRM"),
    ("https://www.w2solution.co.jp/useful_info_ec/medical_ec/", "医薬品EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/metaverse-ec/", "EC メタバース"),
    ("https://www.w2solution.co.jp/useful_info_ec/10344/", "大規模ECサイト"),
    ("https://www.w2solution.co.jp/useful_info_ec/beauty_netshop/", "EC 化粧品・美容事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/8301/", "化粧品 EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/subscription-cart/", "サブスクリプション カートシステム"),
    ("https://www.w2solution.co.jp/useful_info_ec/departmentstore-ec-example/", "EC 百貨店事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-cosmetics/", "D2C 化粧品・美容"),
    ("https://www.w2solution.co.jp/useful_info_ec/4824/", "定期通販 解約理由"),
    ("https://www.w2solution.co.jp/useful_info_ec/regular-purchase-cart/", "単品通販"),
    ("https://www.w2solution.co.jp/useful_info_ec/10351/", "ECベンダー"),
    ("https://www.w2solution.co.jp/useful_info_ec/border-crossing-ec-example/", "越境EC 事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/803/", "ECサイト コンセプト"),
    ("https://www.w2solution.co.jp/useful_info_ec/dx-ec/", "EC DX"),
    ("https://www.w2solution.co.jp/useful_info_ec/4981/", "定期通販 倉庫"),
    ("https://www.w2solution.co.jp/useful_info_ec/live-commerce-ec/", "EC ライブコマース"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-food/", "D2C 食品"),
    ("https://www.w2solution.co.jp/useful_info_ec/881/", "ECサイト 運営代行"),
    ("https://www.w2solution.co.jp/useful_info_ec/eclicense/", "EC業界 資格"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-site-rfp/", "EC RFP"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-application/", "EC アプリ"),
    ("https://www.w2solution.co.jp/useful_info_ec/1396/", "ECサイト ASP"),
    ("https://www.w2solution.co.jp/useful_info_ec/938/", "EC 在庫"),
    ("https://www.w2solution.co.jp/useful_info_ec/10748/", "ユニファイドコマース"),
    ("https://www.w2solution.co.jp/useful_info_ec/virtual-ec/", "EC バーチャル試着"),
    ("https://www.w2solution.co.jp/useful_info_ec/7821/", "自社EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/913/", "ECサイト パッケージ"),
    ("https://www.w2solution.co.jp/useful_info_ec/944/", "EC CMS"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-market/", "EC業界 市場規模"),
    ("https://www.w2solution.co.jp/useful_info_ec/867/", "EC業界知識"),
    ("https://www.w2solution.co.jp/useful_info_ec/point-management-system/", "EC ポイント管理"),
    ("https://www.w2solution.co.jp/useful_info_ec/food-ec-examples/", "食品EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/4413/", "個人ECサイト"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-marketing-howto/", "D2C マーケティング"),
    ("https://www.w2solution.co.jp/useful_info_ec/1005/", "ECサイト 利用規約"),
    ("https://www.w2solution.co.jp/useful_info_ec/2499/", "EC SEO"),
    ("https://www.w2solution.co.jp/useful_info_ec/1379/", "ECサイト 機能"),
    ("https://www.w2solution.co.jp/useful_info_ec/7264/", "ECサイト 要件定義"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-howto-choice/", "ECサイト構築 会社"),
    ("https://www.w2solution.co.jp/useful_info_ec/onlineshop-rule/", "ネットショップ 開業許可"),
    ("https://www.w2solution.co.jp/useful_info_ec/2515/", "ECサイト WordPress"),
    ("https://www.w2solution.co.jp/useful_info_ec/7825/", "ECサイトフルスクラッチ"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-instagram/", "EC Instagram"),
    ("https://www.w2solution.co.jp/useful_info_ec/core-system/", "EC 基幹システム"),
    ("https://www.w2solution.co.jp/useful_info_ec/678/", "EC 店舗"),
    ("https://www.w2solution.co.jp/useful_info_ec/4425/", "ECサイト オープンソース"),
    ("https://www.w2solution.co.jp/useful_info_ec/omni-channel-apparel/", "オムニチャネル事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/subscription-management-system/", "サブスクリプション 管理システム"),
    ("https://www.w2solution.co.jp/useful_info_ec/4402/", "EC アクセス"),
    ("https://www.w2solution.co.jp/useful_info_ec/1389/", "ECカート"),
    ("https://www.w2solution.co.jp/useful_info_ec/970/", "カゴ落ち 対策メール"),
    ("https://www.w2solution.co.jp/useful_info_ec/7970/", "ECモール"),
    ("https://www.w2solution.co.jp/useful_info_ec/4790/", "リピート率"),
    ("https://www.w2solution.co.jp/useful_info_ec/3863/", "EC セキュリティ"),
    ("https://www.w2solution.co.jp/useful_info_ec/2539/", "カゴ落ち 対策"),
    ("https://www.w2solution.co.jp/useful_info_ec/10394/", "ECサイト構築 比較"),
    ("https://www.w2solution.co.jp/useful_info_ec/4811/", "リピート通販 LTV"),
    ("https://www.w2solution.co.jp/useful_info_ec/892/", "ネットショップ開業 資金"),
    ("https://www.w2solution.co.jp/useful_info_ec/1076/", "EC 集客"),
    ("https://www.w2solution.co.jp/useful_info_ec/957/", "EC SNS"),
    ("https://www.w2solution.co.jp/useful_info_ec/7827/", "ECサイト リニューアル"),
    ("https://www.w2solution.co.jp/useful_info_ec/903/", "ネットショップ開業"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-business-model/", "EC事業 ビジネスモデル"),
    ("https://www.w2solution.co.jp/useful_info_ec/980/", "ECサイト 作り方"),
    ("https://www.w2solution.co.jp/useful_info_ec/1717/", "ECサイト構築 相場"),
    ("https://www.w2solution.co.jp/useful_info_ec/601/", "EC 広告"),
    ("https://www.w2solution.co.jp/useful_info_ec/1067/", "EC 施策"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-marketing/", "ECマーケティング"),
    ("https://www.w2solution.co.jp/useful_info_ec/819/", "ネットショップ セミナー"),
    ("https://www.w2solution.co.jp/useful_info_ec/4988/", "EC 受注管理システム"),
    ("https://www.w2solution.co.jp/useful_info_ec/sales_management_system/", "EC 販売管理システム"),
    ("https://www.w2solution.co.jp/useful_info_ec/8551/", "EC業界 トレンド"),
    ("https://www.w2solution.co.jp/useful_info_ec/regular-mail-order/", "定期通販"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-business/", "EC事業"),
    ("https://www.w2solution.co.jp/useful_info_ec/epr-difference/", "EC ERP"),
    ("https://www.w2solution.co.jp/useful_info_ec/649/", "EC 物流"),
    ("https://www.w2solution.co.jp/useful_info_ec/4422/", "定期通販 カートシステム"),
    ("https://www.w2solution.co.jp/useful_info_ec/subscription_about/", "サブスクリプション"),
    ("https://www.w2solution.co.jp/useful_info_ec/1084/", "ECサイト 撮影"),
    ("https://www.w2solution.co.jp/useful_info_ec/840/", "ネットショップ セール"),
    ("https://www.w2solution.co.jp/useful_info_ec/centos-7/", "centos-7"),
    ("https://www.w2solution.co.jp/useful_info_ec/oms-about/", "OMS"),
    ("https://www.w2solution.co.jp/useful_info_ec/829/", "ネットショップ 仕入れ"),
    ("https://www.w2solution.co.jp/useful_info_ec/3856/", "オムニチャネル"),
    ("https://www.w2solution.co.jp/useful_info_ec/ar-ec/", "EC AR"),
    ("https://www.w2solution.co.jp/useful_info_ec/4409/", "休眠顧客"),
    ("https://www.w2solution.co.jp/useful_info_ec/1709/", "ECサイト"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c/", "D2Cとは"),
    ("https://www.w2solution.co.jp/useful_info_ec/950/", "越境EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/wms-about/", "WMS"),
    ("https://www.w2solution.co.jp/useful_info_ec/4979/", "ロジスティクス"),
    ("https://www.w2solution.co.jp/useful_info_ec/tokengatecommerce/", "トークンゲート コマース"),
    ("https://www.w2solution.co.jp/useful_info_ec/btob-ec/", "BtoB EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-oem/", "EC OEM"),
    ("https://www.w2solution.co.jp/useful_info_ec/web-edi/", "Web EDI"),
    ("https://www.w2solution.co.jp/useful_info_ec/order-received-system/", "受発注システム"),
    ("https://www.w2solution.co.jp/useful_info_ec/wholesale-ec/", "卸売 EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/retailmedia/", "リテールメディア"),
    ("https://www.w2solution.co.jp/useful_info_ec/mediacommerce/", "メディアコマース"),
    ("https://www.w2solution.co.jp/useful_info_ec/drop-shipping/", "無在庫販売"),
    ("https://www.w2solution.co.jp/useful_info_ec/shareholder-benefits/", "株主優待 電子化"),
    ("https://www.w2solution.co.jp/useful_info_ec/launch_brand/", "ブランド 立ち上げ"),
    ("https://www.w2solution.co.jp/useful_info_ec/merchandise_sales/", "物販とは"),
    ("https://www.w2solution.co.jp/useful_info_ec/product_selling/", "商品 売れる"),
    ("https://www.w2solution.co.jp/useful_info_ec/food_oem/", "食品 OEM"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec_site_analysis/", "EC サイト分析"),
    ("https://www.w2solution.co.jp/useful_info_ec/f2-conversion/", "F2転換"),
    ("https://www.w2solution.co.jp/useful_info_ec/supplier/", "サプライヤーとは"),
    ("https://www.w2solution.co.jp/useful_info_ec/3d_secure_must/", "3Dセキュア 義務化"),
    ("https://www.w2solution.co.jp/useful_info_ec/purchase_order/", "POとは"),
    ("https://www.w2solution.co.jp/useful_info_ec/rebate/", "割り戻しとは"),
    ("https://www.w2solution.co.jp/useful_info_ec/bopis/", "BOPISとは"),
    ("https://www.w2solution.co.jp/useful_info_ec/partition_price/", "仕切り価格とは"),
    ("https://www.w2solution.co.jp/useful_info_ec/showrooming/", "ショールーミング"),
    ("https://www.w2solution.co.jp/useful_info_ec/aioverviews/", "AIO対策 EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/special_discount/", "出精値引き"),
    ("https://www.w2solution.co.jp/useful_info_ec/employee_sales/", "BtoE"),
    ("https://www.w2solution.co.jp/useful_info_ec/backorder/", "バックオーダーとは"),
    ("https://www.w2solution.co.jp/useful_info_ec/closedsite/", "クローズドサイト"),
    ("https://www.w2solution.co.jp/useful_info_ec/btobtoc/", "BtoBtoC"),
    ("https://www.w2solution.co.jp/useful_info_ec/ai/", "EC AI"),
    ("https://www.w2solution.co.jp/useful_info_ec/btobtob/", "BtoBtoB EC"),
    ("https://www.w2solution.co.jp/useful_info_ec/1312/", "通販サイト 作り方"),
    ("https://www.w2solution.co.jp/useful_info_ec/social-commerce/", "ソーシャルコマース"),
    ("https://www.w2solution.co.jp/useful_info_ec/repeat-order/", "リピート通販"),
    ("https://www.w2solution.co.jp/useful_info_ec/single-item-repeat/", "単品リピート通販"),
    ("https://www.w2solution.co.jp/useful_info_ec/8244/", "アパレルEC"),
    ("https://www.w2solution.co.jp/useful_info_ec/headlesscommerce/", "ヘッドレスコマース"),
    ("https://www.w2solution.co.jp/useful_info_ec/replace/", "EC リプレイス"),
    ("https://www.w2solution.co.jp/useful_info_ec/retailmedia_case/", "リテールメディア 事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/mediacommerce-case/", "メディアコマース 事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-healthy-food/", "EC 健康食品"),
]

# Additional keywords for same URLs
EXTRA_KWS = [
    ("https://www.w2solution.co.jp/useful_info_ec/supplement_netshop/", "ネットショップ 健康食品事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/ec-company/", "EC物流 アウトソーシング"),
    ("https://www.w2solution.co.jp/useful_info_ec/food-ec-examples/", "EC 食品事例"),
    ("https://www.w2solution.co.jp/useful_info_ec/867/", "EC用語"),
    ("https://www.w2solution.co.jp/useful_info_ec/d2c-case/", "D2Cブランド"),
    ("https://www.w2solution.co.jp/useful_info_ec/customerdata-management/", "顧客データ管理"),
]


def seed():
    db.init_db()
    url_to_id = {}

    for url, kw in RAW:
        url_clean = db.normalize_url(url)
        if url_clean not in url_to_id:
            article_id = db.upsert_article(url_clean, main_kw=kw)
            url_to_id[url_clean] = article_id
        else:
            # Same URL, different KW → add as extra KW
            if kw:
                db.add_keyword(url_to_id[url_clean], kw)

    for url, kw in EXTRA_KWS:
        url_clean = db.normalize_url(url)
        if url_clean in url_to_id and kw:
            db.add_keyword(url_to_id[url_clean], kw)

    print(f"Seeded {len(url_to_id)} articles.")


if __name__ == "__main__":
    seed()
